#cloud-config
users:
  - name: lex
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKtXehh5Upeqat+r3OsC1VIh2Rnma/menCG/w9RxlX4r lex@lex-virtualbox

repo_update: true
repo_upgrade: true

runcmd:
  - curl -fsSL https://get.docker.com -o get-docker.sh
  - sudo sh get-docker.sh